### ISSUE TITLE
500 error codes on 404

### ISSUE THREAD

**Issue by dnlup** [immobiliare/fastify-metrics#134]
A `404` generates an internal server error because the plugin tries to send a metric using the `reply` decorator, which in turn checks for the presence of a `routeId` inside the `metrics` object. This object is not setup for a route that doesn't exists because we use the `onRoute` hook to do it. We should take this into account in the `onError` hook.

**Comment by dnlup** [comment]
While I am working on it, I see that every hook has this problem, not just the `onError` one. So I think we should move the check inside the decorators.

**Comment by antoniomuso** [comment]
I think we can check in both cases.
