### ISSUE TITLE
Allow to pass custom client instance

### ISSUE THREAD

**Issue by dnlup** [immobiliare/fastify-metrics#35]

**Comment by antoniomuso** [comment]
We have to define a standard interface for the client. Do we want to maintain the Dats interface?

**Comment by dnlup** [comment]
> We have to define a standard interface for the client. Do we want to maintain the Dats interface?

Yes, my idea was allowing a custom Dats instance.

**Comment by simonecorsi** [comment]
> Yes, my idea was allowing a custom Dats instance.

Seems nice a good feat, it may be useful both for testing that for custom usages!
