### ISSUE TITLE
Add a benchmarks workflow

### ISSUE THREAD

**Issue by dnlup** [immobiliare/fastify-metrics#45]
It might be useful to get a basic view on the performance impact of the PRs.

**Comment by antoniomuso** [comment]
I like it, but is CI reliable?

**Comment by dnlup** [comment]
> I like it, but is CI reliable?

I wouldn't say it's that reliable. But it's not a lot of work to add it and it can give a few info on the PR. I think it's worth it.

**Comment by antoniomuso** [comment]
LGTM
