### ISSUE TITLE
Config options refactor

### ISSUE THREAD

**Issue by dnlup** [immobiliare/fastify-metrics#54]
Scope requests/respose flags inside a dedicated key. Use the health key to pass custom sampler options too.

**Comment by dnlup** [comment]
As cited in [here](https://www.fastify.io/docs/latest/Reference/Plugins/#plugin-options), a plugin should scope its config akin a dedicated key, sou we may have to scope everything under a `metrics` key too.

**Comment by dnlup** [comment]
@simonecorsi This goes along what we discussed while reviewing #66 . We could avoid nesting and scoop everything under `metrics`.

**Comment by simonecorsi** [comment]
> @simonecorsi This goes along what we discussed while reviewing #66 . We could avoid nesting and scoop everything under `metrics`.

sgtm, we can do it here tho 👍
